# Generated by Django 2.2 on 2019-04-22 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_auto_20190422_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='file',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='file_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
