# Generated by Django 2.2 on 2019-04-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.University'),
        ),
    ]
